### ISSUE TITLE
Apple Silicon Mac でインストーラーが Rosetta を要求してしまう

### ISSUE THREAD

**Issue by dayflower** [codefirst/aquaskk#101]
実際は (最新のものは) Universal binary ですが、 Rosetta 2 を未インストールの状態でインストーラーを起動すると、 Rosetta 2 のインストールを要求してしまいます。

https://developer.apple.com/forums/thread/667672 こちらのサイトによると、

[distribution.xml](https://github.com/codefirst/aquaskk/blob/master/platform/mac/pkg/distribution.xml#L10) の `<options>` タグに `hostArchitectures="x86_64,arm64"` 属性を追加すると、 Rosetta 2 のインストールを要求されなくなるようです。

(実際手元で pkgutil で展開し書き換えてインストールしてみたところ、 Rosetta 2 のインストールを要求されることなく、インストールおよび実行が可能でした; ご報告まで)

**Comment by banjun** [comment]
@dayflower  そういうパターンがあるんですね。対応方法記載ありがとうございます。もしPRいただけるなら確認して取り入れたいと思います。

**Comment by banjun** [comment]
pkgを開いたとき

<img width="688" alt="image" src="https://user-images.githubusercontent.com/11156/102693023-d56b4900-425a-11eb-9fe3-278401416810.png">

`[今はしない]`

<img width="732" alt="image" src="https://user-images.githubusercontent.com/11156/102693029-db612a00-425a-11eb-837e-f54047a28a0b.png">

**Comment by banjun** [comment]
Rosettaなし環境再現確認は、SIPを無効にしていれば `sudo mv /Library/Apple/usr/libexec/oah{,.bak}` でOK (たぶん)
