### ISSUE TITLE
送り仮名の区切り文字 '*' をカスタマイズ可能に

### ISSUE THREAD

**Issue by yasuhito** [codefirst/aquaskk#11]
はじめまして、AquaSKK を愛用しております。

AquaSKK を Markdown エディタの Ulysses III で使うと、インラインで表示される確定前の送り仮名の区切り文字 '\*' が Markdown での強調の '*' と解釈されてしまい、確定前のインライン表示が崩れてしまいます。

これをカスタマイズできるオプションを追加していただけると助かります!

ちなみに手元では https://github.com/codefirst/aquaskk/blob/master/src/engine/editor/SKKOkuriEditor.cpp#L41 を次のように Markdown とぶつからない文字に修正してうまく使えています。

```c++
void SKKOkuriEditor::WriteContext() {
   context()->output.Compose("^" + okuri_);
```

**Comment by mzp** [comment]
Ulysses IIIだとつらい感じになるのは確認しました。

ただ申し訳ないですが、以下の理由ですぐ対応するのは難しいです。

 * 埋め込まれている文字列は「▼、▽、....」などいろいろな種類があり、全種類リストアップするのは難しい
 * それ用のUIを作るのも大変
 * AquaSKKとしてはシステムに「未確定文字列」として渡している部分に対して、プレビュー処理をしているUlysses IIIの処理が妥当とは言えない
    * 実際、同じくMarkdownエディタである[Kobito](http://kobito.qiita.com/ja)では、この問題は発生しない

#12 についても同様です。

**Comment by yasuhito** [comment]
Ulysses III 自体の問題ということですね。
自分用にビルドすれば問題なく使えますので、#11 #12 は閉じます。
ありがとうございました!
