### ISSUE TITLE
IntelliJでのq/l問題 (2022.05)

### ISSUE THREAD

**Issue by yokoiwa** [codefirst/aquaskk#111]
以前4.2.4で解消されていたIntelliJでのモード切り替え時のq/l問題が再発?しています。
see: https://github.com/codefirst/aquaskk/pull/10

パソコンの買い替えや環境の変更をはさむため、どこかのバージョンで再発するようになったのか、はたまた私の環境だけの問題なのかは定かではありません。

以下、環境です。
AquaSKK 4.7.4
JetBrains Rider 2021.3.3
macOS Monterey 12.2.1

**Comment by mikanIchinose** [comment]
おなじく発生しています
AquaSKK 4.7.3
Android Studio Chipmunk | 2021.2.1 Patch 1
macOS Monterey 12.4

**Comment by mikanIchinose** [comment]
https://mzp.hatenablog.com/entry/2016/10/29/095435
> [AquaSKK](http://d.hatena.ne.jp/keyword/AquaSKK)レベルでJetBrains製品に対応するのをあきらめた。C-j/l/q/L/Qを使用可能にするために、Karabinerを利用するようにした。

Jetbrains対応はやめたみたい
記事にあるようにKarabiner-elementsで対応すればよさそうです

**Comment by lonsagisawa** [comment]
経緯としてはmzp氏によるJetBrains製品への個別対応をやめるとした記事が出た後に、 #48 でその辺の互換性まわりのworkaroundを使用者側で設定できるようにしたといった具合になっています。ですのでKarabiner-Elementsでの個別設定は不要です。お手数ですがlやqなどの抜けがある場合は設定画面で互換性まわりをいろいろ触ってみてください。

**Comment by lonsagisawa** [comment]
JetBrains製品についてはまったく使っていないので私はわからないのですが、mzp氏の記事などを見るに以前はそもそも入力モードの変更自体が動いていなかったのではないかと思います。入力モードの変更がKarabiner-Elementsなしで動作するようになり、環境設定でのworkaroundだけで問題なく使用できるようになったのであればREADMEやWikiの記述はいじらないといけないかもしれません。

**Comment by yokoiwa** [comment]
@mikanIchinose 
おお、空文字挿入だけでいけたのですね。
こちらでも互換設定のみで正常に動作することが確認できました。
たいへん助かりました。ご検証ありがとうございます！
