### ISSUE TITLE
AquaSKK起動時のデフォルト入力モードを「ひらかな」ではなく「ASCII」にしたい

### ISSUE THREAD

**Issue by rkarsnk** [codefirst/aquaskk#114]
現在、エディタやブラウザなどの文字入力領域のフォーカスを移動させた時、自動的に「ひらかな」モードになります。
これを「ASCII」モードをデフォルトにしたいのですが、何か方法あるでしょうか?

ソースコードのどこかに関連する記載がありますか?

以下の環境で利用しています。
- macOS Monterey 12.6.1 (Intel)
- AquaSKK 4.7.4

入力モードは、以下を有効にしています。
- ASCII
- ひらかな
- カタカナ
- 半角カナ
- 全角英数

**Comment by lonsagisawa** [comment]
こちらの環境では見たことのない症状です(macOS Ventura 13.0, ARM, AquaSKK 4.7.4ですが、Big Surで今のMacを使いはじめた頃からデフォルトはASCIIになっています)。入力ソースリストはこんな感じで、ABCが居座っている以外は同じような状況です。

<img width="827" alt="スクリーンショット 2022-10-31 21 40 51" src="https://user-images.githubusercontent.com/5173607/199010133-1da46c8b-d812-4c66-948e-56a1363c37e4.png">

メニューバーの入力ソースリストからASCIIとひらかなを何度か切り替えた後、JISキーボードであれば英数とかなを1回ずつ押してみて正常に切り替わるか確認してください。また入力モードはこのモードではアプリケーションごとではなくグローバルに保持されるので、ひらかなの状態で他のアプリケーションにフォーカスを移すとモードがひらかなのままになるのは仕様どおりとなります。

またKarabiner-Elementsなどキーボードに干渉するアプリケーションを使っているのであれば、どのような設定をしているかも含めて教えていただけるとメンテナーが調査をする際に役に立つのではないかと思います。

**Comment by lonsagisawa** [comment]
「元々使っていたアプリケーションでの入力モードにかかわらず、フォーカスを他に移したらASCIIに戻るようにしたい」とかだと、たぶん新機能として実装しなきゃいけないと思います…………。

**Comment by rkarsnk** [comment]
> メニューバーの入力ソースリストからASCIIとひらかなを何度か切り替えた後、JISキーボードであれば英数とかなを1回ずつ押してみて正常に切り替わるか確認してください。また入力モードはこのモードではアプリケーションごとではなくグローバルに保持されるので、ひらかなの状態で他のアプリケーションにフォーカスを移すとモードがひらかなのままになるのは仕様どおりとなります。

私の環境では、「ABC」の入力ソースは削除済みで、AquaSKKのひらがな、カタカナ、半角カナ、全角英数、ASCIIのみが表記されており、SKKのキーバインドのみで入力モードが切り変わるようになっています。利用しているキーボードはHHKB USです。

入力モードについては、macOS起動直後が「ひらかな」になってしまうので、起動直後は「ASCII」となるようにしたいと思っています。

<img width="657" alt="SKK-Config" src="https://user-images.githubusercontent.com/26945036/199853883-639cd3f0-a600-4899-9eb3-e0784b95e2f3.png">

Karabiner-Elementsでは、図の様にTerminal用の設定が追加されているだけになります。

<img width="660" alt="SKK-Karabiner" src="https://user-images.githubusercontent.com/26945036/199853880-1d775471-5bcd-4f5b-8e24-9d75213a28ad.png">

以下は、Windows用のCorvusSKKの画像になりますが、「初期入力モード」の設定のようなことができないかな、と考えています。(画像はhttps://github.com/nathancorvussolis/corvusskk より取得し、編集)
![103_behavior_1](https://user-images.githubusercontent.com/26945036/199854737-428b2640-1528-4673-bbd4-7d07ddb655c5.png)
