### ISSUE TITLE
Qtアプリケーションで日本語入力をすると、モード切り替え時にl/L/qの文字も入力されてしまう

### ISSUE THREAD

**Issue by bravotan** [codefirst/aquaskk#16]
#10と似た現象ですが、Qt4、Qt5どちらでも発生します。

環境
AquaSKK 4.2.4 (2015-03-20)
OSX 10.8 MountainLion

**Comment by mzp** [comment]
具体的なQtアプリケーション名をあげていたけると助かります。

**Comment by bravotan** [comment]
Qtアプリケーション全般なんですが、例としてはQtCreatorのエディタ画面で、入力モードを切り替えると切り替え時のキーもタイプされてしまいます。

ひらがなモードで「aiueoqaiueoqaiueolaiueo(Ctrl+j)Laiueo」と入力すると以下のように印字されます
「あいうえおqアイウエオqあいうえおlaiueoLａｉｕｅｏ」

実際の画像も念のため貼ります。
![2015-05-07 9 24 15](https://cloud.githubusercontent.com/assets/6016409/7506437/eee200a4-f49a-11e4-8f30-cca9b45ab01a.png)

**Comment by mzp** [comment]
ありがとうございます。確認します。

**Comment by mzp** [comment]
現象を確認しましたが Java製アプリと異なり、あとからQt製のアプリかどうかを判断することはできないので同じ回避方法は使えません。

Qtの不具合という認識ですので bug reportsを作成しました。 https://bugreports.qt.io/browse/QTBUG-46300

**Comment by bravotan** [comment]
調査ありがとうございました。Qt側のバグ扱いということで了解です。
