### ISSUE TITLE
辞書表示時に読みも尊重してほしい

### ISSUE THREAD

**Issue by konn** [codefirst/aquaskk#18]
AquaSKKでは変換時にSKK辞書の注釈といっしょに、OS X標準搭載の「辞書.app」の内容を表示してくれてとても便利なのですが、読みの情報は無視して字面だけで検索結果が出ます。
だいたい意味は同じ場合が多いので問題ないといえばないのですが、検索結果が複数あった場合、変換前のひらがな表記に基づいて表示するものを選択するように出来ないでしょうか？

**Comment by mzp** [comment]
nice idea!

**Comment by mzp** [comment]
確認しましたが非常に難しいです。

 * 辞書の検索は DCSCopyTextDefinition [MacAnnotator.mm#L47](https://github.com/codefirst/aquaskk/blob/31093adfcbdd4a074dc1612996f43096fe77a287/platform/mac/src/server/MacAnnotator.mm#L47) を用いているが、これは単語から定義を引くだけのAPI。
 * 読みの指定や、同名の見出し語を複数取得する機能はない。(参考: [Dictionary Services Reference](https://developer.apple.com/library/mac/documentation/UserExperience/Reference/DictionaryServicesRef))

という理由から、読みを指定して辞書を検索することや、検索結果から読みの一致するものを選ぶのは難しいです。

それはそれとして、この調査の途中で、アンドキュメンティッドながら辞書の種類指定がでるらしいので、和英辞書ではなくて大辞林から検索するようにしてもいいかもですね。

**Comment by konn** [comment]
なるほど……。APIの制限で仕方ないわけですね。
和英を無効化して検索するのは、結構便利な気がするので良いと思います。
（あるいは環境設定で対象辞書を指定出来ると良いのかも？）

**Comment by banjun** [comment]
辞書.appの環境設定で大辞林を和英より上にするのはどうでしょう。

**Comment by konn** [comment]
ああなるほど。辞書.appでの設定がグローバルに結果に影響するんですね。
それならその旨をどこかに書いておけば問題は無い気がします。

**Comment by mzp** [comment]
とりあえずこのissuesとしてはcloseで。
