### ISSUE TITLE
Developer IDの署名を付けてリリースする

### ISSUE THREAD

**Issue by banjun** [codefirst/aquaskk#20]
ゴール

- [ ] Gatekeeperの設定でapps from identified developersを許可しているときに警告なくインストールできる

サブタスク

- [ ] make pkgを新しくして，署名できる形式のpkgをつくる (バンドル形式ではなくフラット形式のもの)
- [ ] 署名フローをコマンド化する
- [ ] 署名してリリースページに置く

**Comment by mzp** [comment]
つけました。
