### ISSUE TITLE
AZIK有効時の Shift + ; の入力について

### ISSUE THREAD

**Issue by Warashi** [codefirst/aquaskk#27]
AZIK有効時の Shift + ; (セミコロン) の入力は、漢字入力もしくは送り仮名入力の開始と共に「っ」が入力されて欲しいのですが、現状では単に「+」が入力されるようです。
なにか方法があればご教示ください。

**Comment by mzp** [comment]
詳細はこれから確認します。

ただ、SKKの辞書がローマ字前提のため、「っ」での送り仮名入力開始は限定的な対応になります。(参考: https://github.com/codefirst/FlickSKK/issues/27)

**Comment by mzp** [comment]
回避方法としては「T;」で「っ」はじまりの変換ができます。

がShift + 「;」を使えるようにしたいですねー。

**Comment by semialt** [comment]
かな定義に
+,っ,ッ,+
を追加し、
keymap.conf でUpperCasesを
UpperCases		group::A-Z||+UpperCase

**Comment by Warashi** [comment]
適当にskkservをでっちあげてddskkではどういう挙動をするのか見てみたんですが、一律で t 始まりの送りと見なされる模様?のようです。

**Comment by mzp** [comment]
https://github.com/codefirst/aquaskk/releases/tag/4.3.0 で対応しました。
