### ISSUE TITLE
AZIK入力時のカナ変換、および「ん」について

### ISSUE THREAD

**Issue by Warashi** [codefirst/aquaskk#29]
AZIKでは、「ん」を入力するのに「q」を使うこととなっており、ddskkのazik実装では衝突したカナ変換を「@」に再割り当てしています。
デフォルトのルールはddskkに従う方が混乱が少ないのではないかと考えているのですが、どうでしょうか。

(参考: http://openlab.ring.gr.jp/skk/skk-manual-git/AZIK.html )

**Comment by mzp** [comment]
現状だけ説明しますと、AquaSKKで各ルールが拡張できるのはローマ字変換ルールのみで、切り替えキーの拡張は難しいんですよねぇ。

なんとかしたい気はします。

**Comment by mzp** [comment]
https://github.com/codefirst/aquaskk/releases/tag/4.3.0 で対応しました。

**Comment by Warashi** [comment]
4.3.0を試しましたが、azik.rule で 「q」と「ん」との対応がコメントアウトされたままになっているようで、入力できません。
修正をお願いします。

**Comment by mzp** [comment]
おっと忘れてました。 https://github.com/codefirst/aquaskk/releases/tag/4.3.1 をお試しください。

**Comment by Warashi** [comment]
4.3.1でも入力できません。
自分で設定を書き換えたことがないので予想になりますが、azik.ruleの半角カナのフィールドがないことが原因ではないでしょうか。

**Comment by mzp** [comment]
うう、すいません。今度こそいけるはずです。

https://github.com/codefirst/aquaskk/releases/tag/4.3.2

**Comment by Warashi** [comment]
入力できました。素早い対応ありがとうございます。

**Comment by mzp** [comment]
:tada:
