### ISSUE TITLE
AZIK入力時の「ー」(長音) 入力について

### ISSUE THREAD

**Issue by Warashi** [codefirst/aquaskk#30]
AZIKでは、「：」で「ー」を入力することとなっています。
(参考: http://hp.vector.co.jp/authors/VA002116/azik/azikinfo.htm )

各々がかな入力ルールを書き換えるのでもいいのかもしれませんが、できればデフォルトで取り込んでいただきたいと思います。

**Comment by mzp** [comment]
https://github.com/codefirst/aquaskk/releases/tag/4.3.0 で対応しました。
