### ISSUE TITLE
LINE上で辞書登録の入力待ち状態でカナトグルすると表示が消える

### ISSUE THREAD

**Issue by Warashi** [codefirst/aquaskk#36]
例えば、
Aaa[SPC]
などと入力すると
[登録：あああ]
と表示されますが、 この状態で「q」(AZIKなら「@」) キーを押すとLINEの入力欄の表示から登録単語読みの表示が消えます。
バグだと思うのですが、LINE以外では今のところ再現していません。

**Comment by mzp** [comment]
LINEおよびJavaアプリケーションは、InputMethodの扱いに難があり、そのための回避コードをいれています。(参考: #13)

おそらくそれが原因ですが、LINE側が修正されない限り対応は困難です。
