### ISSUE TITLE
Office 2016のExcelで日本語入力をすると、モード切り替え時にl/L/qの文字も入力されてしまう

### ISSUE THREAD

**Issue by zalt50** [codefirst/aquaskk#37]
#16 と似てます。環境は以下の通りです。

AquaSKK 4.3.2 (2015-11-08)
Microsoft Excel for Mac 15.15 (151008)

同じOffice 2016のWordとPowerPointでは、モード切り替え時にl/L/qが入力されてしまうことはありません。

**Comment by mzp** [comment]
症状からすると #13 や #14 と同様の方法で直りますが、自分がOffice 2016を所持していないので、対応はなかなか難しいですね。

**Comment by mzp** [comment]
4.3.3 https://github.com/codefirst/aquaskk/releases/tag/4.3.3 としてリリースしました。
