### ISSUE TITLE
Ulysses for Mac上における送りがなの挙動

### ISSUE THREAD

**Issue by hebop** [codefirst/aquaskk#40]
Ulysses for Mac2.2.1(24168)上において、例えば「受け」や「持つ」といった単語を入力しようとすると"う＊え＊k"、"も＊う＊t"のようになり、c-gのキャンセルも効かなくなります。
「言い」「言う」「据え」などは問題なく入力できるところを見ると、送りがなの最初の文字が母音じゃないと挙動がおかしくなるようです。
4.3.2と4.3.3にて確認、OSは10.10.3(4.3.2)と10.11.2(4.3.3)です。

**Comment by hebop** [comment]
あれ、うまく表示されてない。"う＊え＊k"、"も＊う＊t"のようになるのです。

**Comment by mzp** [comment]
本件は、Ulyssesのふるまいが原因で生じる問題のため、AquaSKK側での対応は困難です。(案自体は#11 ででてますが...)

ので、 http://www.ulyssesapp.com 側にfeedbackを送るのがよいと思います。 私からは送信しましたが、数があったほうが対応優先度が上ると思いますので、よろしければご検討ください。

**Comment by hebop** [comment]
#11を確認いたしました。このissuesは閉じます。ありがとうございました。

**Comment by mzp** [comment]
Ulyssesから「対応チケットはつくったよ」みたいな返信はありました。(いつ対応するとは言っていない)
