### ISSUE TITLE
4.3.4でのkeymap.conf設定

### ISSUE THREAD

**Issue by kawauso** [codefirst/aquaskk#44]
ファイルkeymap.confにて
ToggleKana		hex::0x3b
ToggleJisx0201Kana	hex::0x3a
と設定している場合、Aqua4.3.3は設定の意図通りに動作しますが、Aqua4.3.4では動作しませんでした。

**Comment by mzp** [comment]
すいません。AZIK対応のためにToggleKanaとかの設定よりkana-rule.confを優先するようにしてしまいました。

意図した挙動を得たい場合は、0x3aと0x3bをInputCharsの範囲外にしてください。

```
InputChar group::hex::0x20-0x30,0x3c-0x7e
```
