### ISSUE TITLE
Google Apps Script Editorでの不具合

### ISSUE THREAD

**Issue by sugitach** [codefirst/aquaskk#47]
いつも便利につかわせていただいています。
今日、Google Apps Script Editor( https://script.google.com/ からエディタにはいれます ) 上で入力しようとしたところ、変換直後の表示がひらがなのまま変化せず、確定したところで漢字に置き換わるという現象に気がつきました。
Chrome で気がついたのですが、 safari で試してみたところ同じ状態になりました。
通常のフォーム入力では問題ないので、aquaskkで対応できることではないのかもしませんが、一度ご確認いただけないでしょうか。

**Comment by mzp** [comment]
標準のInputMethodでも再現しますし、AquaSKK側での対応はできないです。

GoogleApScriptのほうにバグレポは出しました。

https://code.google.com/p/google-apps-script-issues/issues/detail?id=6363&thanks=6363&ts=1474713638
