### ISSUE TITLE
日本語入力時、特定のアプリでのみ全角スペースが有効になるようにして欲しい。

### ISSUE THREAD

**Issue by SUPER-SUPREME-SURPRISINGLY-SOMEONE** [codefirst/aquaskk#51]
Word2016で、
縦書きの時に半角スペースのままだと使い難いので、
是非よろしくお願いします‼︎

**Comment by banjun** [comment]
`z ` (z + スペース) でどうでしょうか?
https://github.com/codefirst/aquaskk/blob/master/data/config/kana-rule.conf#L268

**Comment by SUPER-SUPREME-SURPRISINGLY-SOMEONE** [comment]
やはり、それでないとダメですかね…
対応は難しいですか…？

**Comment by banjun** [comment]
z + 何か，の変換も慣れるとWordに限らずどこでも使えてむしろ便利ですよ 👍

**Comment by SUPER-SUPREME-SURPRISINGLY-SOMEONE** [comment]
そうなんですね…
ご教授、感謝します‼︎
でも、対応をちょっとだけ期待してます。
唯一、キータイプが少なくて済むIMEなので😃
