### ISSUE TITLE
変換時の▽が無いモードが欲しい

### ISSUE THREAD

**Issue by dnpp73** [codefirst/aquaskk#53]
試しに https://github.com/dnpp73/aquaskk/commit/606f3d2696bb0103d8b1f6584a71b31d24804b02 で実装してみたんですけど、もし設定の UI を作って ON/OFF 出来るようにすれば取り込んでもらえたりするでしょうか？

**Comment by mzp** [comment]
便利になる人がそれなりにいるようでしたら、取り込みたいなと考えています。

どういう時に▽等がないほうが便利なのでしょうか? 見た目上、▽が邪魔になるからでしょうか?

**Comment by dnpp73** [comment]
単純に見た目だけかなぁと。僕はそんなに困ってないんですけど、友人（サンプル一人だけ）が▽無いバージョン欲しいなーって言ってるのを見たので試しに実装してみた感じです。

**Comment by mzp** [comment]
なるほど。

たしかに文字で入力モードを表現するのは、今風じゃないし気になりますね。また、この辺の文字を誤認してしまう行儀のよくないアプリケーションも存在します。 https://github.com/codefirst/aquaskk/issues/11

ただ、SKKには `▽`、`▼`以外にも、送り仮名の区別するための `*` や、単語登録に使う `[]` 等もあるので、ここだけ直すと中途半端になってしまうのが心配です。

**Comment by dnpp73** [comment]
確かに、たまに行儀の悪いアプリ（主に GUI を Cocoa ネイティブのものじゃないもので自前実装しているやつ）で▽のゴミが残ってしまうものがありますよね。

なるほど、その辺の一貫性を考えた上で今風にするならば `▽` `▼` 以外の `*` とか `[]` もやめて、特別な UI を実装すべきなのかなぁとは思いました。
現に今もこの文章を打っていて、変換モードなのかどうかが下線だけだと分かりにくいなという気持ちにもなってます…

**Comment by mzp** [comment]
> その辺の一貫性を考えた上で今風にするならば `▽` `▼` 以外の `*` とか `[]` もやめて、特別な UI を実装すべきなのかなぁとは思いました。

そうですね。そういうUIがあったら、ボクも使ってみたいですし、オプションとして取り込んでみたい気がします。

**Comment by banjun** [comment]
特別なUIって試してみたい気がしますけど、どういうふうに実装するといいんでしょうね？ たたき台とかあります？

**Comment by mzp** [comment]
とりあえず、いったん閉じますね。
