### ISSUE TITLE
設定画面 - 辞書を追加する際の挙動について

### ISSUE THREAD

**Issue by mlny** [codefirst/aquaskk#55]
## 環境
* OS X 10.11.6
* AquaSKK 4.4.0 (2016-5-7)

## 現象

1. 設定画面内の辞書タブ内で辞書を追加します。
2. 場所の選択... より辞書ファイルを選択すると、先頭にfile:/という文字がついたファイルのパスが追加されます。
3. 実際はパスからfile:/を除去しないと追加した辞書が反映されません。

![9 -01-2016 23-25-17](https://cloud.githubusercontent.com/assets/5173607/18171015/6785e372-709b-11e6-99c9-c504ad60bc48.gif)

**Comment by mzp** [comment]
そうですね。これは薄々気付いてた問題なので直します。

**Comment by mzp** [comment]
https://github.com/codefirst/aquaskk/releases/tag/4.4.1 で修正しました。
