### ISSUE TITLE
かなモードで「n」、「o」と入力すると「の」では無く「んお」と入力される

### ISSUE THREAD

**Issue by lambdadbmal** [codefirst/aquaskk#63]
ver.4.4.2で発生。ver.4.4.1では発生せず。
付属のkarabiner用private.xmlは利用せず。
表題以外にもシフトキーを押下しない入力では子音の入力が捨てられてしまっているように見える。

**Comment by mzp** [comment]
その挙動は特定のアプリケーションでのみ発生するのでしょうか? それともすべての入力エリアで発生するのでしょうか?

**Comment by lambdadbmal** [comment]
Finderの検索テキストボックス
JetBrains Intellijのエディタ
Google Chromeのテキストボックス、URL入力欄
MS Excel 2011
Carbon Emacs
…
場所を問わず発生しております。

**Comment by mzp** [comment]
finderとchromeで確認してみましたが、私の環境(macOS 10.12.1)では発生しないですね。

一度、設定内の「互換性設定」に変な項目がないかを確認してもらえないでしょうか?

**Comment by lambdadbmal** [comment]
こちらの環境は
OS X EI Captan (10.11.6)です。
互換性設定から全ての項目を削除してみましたが、状況は変わらず現象が発生しております。

**Comment by mzp** [comment]
もしかしてAquaSKK統合をお使いでしょうか。 

完全に失念してた&&デグレしていたので、修正しました。

**Comment by lambdadbmal** [comment]
統合モードを利用していることを明記すべきでした。すみません。
ver.4.4.3 + OS X EI Captan (10.11.6)で問題が解消したことを確認いたしました。
本件はcloseいたします。
