### ISSUE TITLE
Sierraで修飾キーの設定などを有効にする

### ISSUE THREAD

**Issue by y-yu** [codefirst/aquaskk#69]
はじめまして。MacBook Pro（13-inch, Late 2016）において次のような問題が発生し、それの解決（？）方法がわかりましたので報告します。

## 問題

MacBook Pro（13-inch, Late 2016）のmacOS Sierraにおいて、AquaSKKを用いた状態でOSの「修飾キー」の設定を変更してもそれが正常に動作しない。またTouch Barのミュート機能も動作しなくなる。

## 試したこと

AquaSKK 4.4.4にて、次の操作を行ったところ症状が解決した。

1. 「システム環境設定」を開き、「セキュリティとプライバシー」を押す
2. 次のように「プライバシー」タブで`/Library/Input Methods/AquaSKK.app` を追加し、チェックを入れる<img width="665" alt="image" src="https://cloud.githubusercontent.com/assets/612043/20489165/f5711e54-b04c-11e6-90d2-dc940401218f.png">
3. コンピュータを再起動する（不要かも）

このようにしたところ、修飾キーの設定が正しく反映されTouch Barのミュート機能も使えるようになりました。
以上よろしくおねがいします。

**Comment by mzp** [comment]
まじすか..。 確認します。

**Comment by mzp** [comment]
うーん、ぼくもMacBook Pro (13-inch, Late 2016, Four Thunderbolt 3 Ports)なんですが再現しないですね。

OSのバージョンが 10.12.2 Beta (16C53a) なので、そのせいかもしれないですが、よくわかりませんね...。

**Comment by mzp** [comment]
ミュートもききますし。

**Comment by y-yu** [comment]
うーん、再現しないようなら、いったんクローズいたします……。
