### ISSUE TITLE
送り仮名が「ゐ」「ゑ」のときに変換ができない

### ISSUE THREAD

**Issue by s-i-d-a-s** [codefirst/aquaskk#70]
El CapitanでAquaSKK4.4.4を使っています。
タイトル通り、「用ゐ」や「植ゑ」などを変換しようとしても、登録モードになってしまい変換ができません。
ユーザ辞書には登録されているのですが、実際の入力では何度試しても新規登録モードになってしまいます。
新規に辞書を作成して試してみたのですが、やはり駄目でした。
問題の所在が判らないので、ご教示いただければと思います。
参考までに、現在のkana-rule.confとkeymap.confを以下に上げておきます
https://github.com/s-i-d-a-s/aquaskk-setting
どうぞよろしくお願いします。

**Comment by NaokiMatsuzaki** [comment]
辞書のエントリが
もちw /用/
うw /植/
の状態では変換できませんでしたが、
もちy /用/
うy /植/
を登録したところ、変換できるようになりました。なお、変換時はMochiWi, UWeと入力しました。
ご参考まで。

**Comment by s-i-d-a-s** [comment]
新たにskk-jisyo.kiukanaという辞書を作成して仰る通りに登録してみたところ、変換できるようになりました。
ひとまずこの方法で旧かなの変換はやってみようと思います。ありがとうございます！

**Comment by NaokiMatsuzaki** [comment]
変換できたとのことで安心しました。その後原因が分かりましたので報告します。jconv.cpp 内でゐ・ゑのローマ字がyi, yeと定義されていたためで、 #71 でwi, weに直したら、元の辞書で変換できるようになりました。

**Comment by s-i-d-a-s** [comment]
原因の特定ありがとうございます。 #71 を拝見しましたが、デフォルトのkana-rule.confですと、“xwi”で「ゐ」、“xwe”で「ゑ」を打つようになっているので、その場合はxwi、xweの定義をする必要がありそうですね。「うぃ」や「うぇ」を送り仮名として使うことはまず無いと思われるので衝突の心配はしなくても大丈夫でしょうか。知識が足りず疑問ばかりで恐縮ですが、お礼を兼ねて書き込んでおきます。どうもありがとうございました。

**Comment by NaokiMatsuzaki** [comment]
ご懸念の点についてですが、kana-rule.confの設定に関わらず、jconv.cppの設定が辞書ファイルのローマ字と一致していれば変換できると思います。ゐ・ゑの送り仮名はSKK-JISYO.Lにはwで登録されていますので、そちらに合わせました。

**Comment by mzp** [comment]
対応ありがとうございます。おっしゃる通りSKK-JISYO.Lにあわせるのがよいと思うので、 #71 を取り込みました。

あとせっかくなので、 旧かな用の拡張設定を追加しようと思います #73
