### ISSUE TITLE
メニューバーを暗くしていると、ASCIIモードを使用している際にアイコンの視認性が悪くなる

### ISSUE THREAD

**Issue by mlny** [codefirst/aquaskk#75]
# 環境
* macOS Sierra 10.12.4 16E195
* AquaSKK 4.4.5 (2016-12-24)

# 現象
タイトルに書いた通りです。言葉で説明するよりもスクリーンショットを見ていただくのが早いと思います。

![2017-04-25 0 55 49](https://cloud.githubusercontent.com/assets/5173607/25347455/f4f34eac-2955-11e7-84a9-c2e2e1a815c4.png)
![2017-04-25 0 55 34](https://cloud.githubusercontent.com/assets/5173607/25347457/f7100d4c-2955-11e7-99bf-85c26d26518d.png)

また、アイコンをクリックすると出るメニュー上では、アイコンは正常に表示されています。

![2017-04-25 1 22 37](https://cloud.githubusercontent.com/assets/5173607/25347663/a73aa150-2956-11e7-99e8-7866a48f4b39.png)

# 再現
1. システム環境設定→一般 にて、「メニューバーとDockを暗くする」をONにします。
2. 入力ソースの設定にて、AquaSKK統合ではなくAquaSKKの個別の入力モードを追加していきます。
3. AquaSKKをASCIIモードにします。

実際とても些細な問題であり実用上は全く問題ないのですが、macOSに詳しくない人としては不思議な現象に見えたのでIssueにしてみることにします。修正が難しいようであれば仕様としてCloseして頂いても大丈夫です。

**Comment by mzp** [comment]
mojaveでdark modeが導入されたことで重要度が増したので調査したんですが、あんまりいい解決策がなさそうなんですよね。

 1. 標準の日本語入力のようにモノクロ画像のアイコンにして、色が反転するようにする。
 2. 白抜きでなくて透明色にする。
 3. あきらめる

1と2は反転しないときのやつにだいぶ影響がでてしまうのでどうしようかなーと思っています。

**Comment by mlny** [comment]
![2018-08-31 21 59 09](https://user-images.githubusercontent.com/5173607/44913708-1d53c280-ad69-11e8-9374-437f5875c50d.png)
4.6.0でアイコンの色合いが調整され、問題が解決したのを確認しました。closeします。
