### ISSUE TITLE
候補ウィンドウのフォント初期設定について

### ISSUE THREAD

**Issue by yosiot** [codefirst/aquaskk#76]
標題の件が AquaSKK の仕様なのかどうか計り兼ねています。
現状の仕様だとしても，可能であれば対応していただきたく思い，
投稿します。

動作環境：macOS 10.13.2 で AquaSKK 4.4.5 を利用しようとしま
          した
  ・通常の運用では OS 起動時にロードするフォントの種類を
    かなり制限しています … ふだんの私には多種はいらない

症状と経過
 1. AquaSKK のインストーラーの指示に従い，インストール終了
 2. 再ログインし，System Preferences > Keyboard >
    Input Source で AquaSKK を追加
 3. メニューバーの表示を AquaSKK に切り替え
     ・Finder の画面に回るビーチ・ボールが表示されたままで，
       いつまでも状況は変らない
     ・AquaSKK のプルダウン・メニューを見ると「環境設定」
       以下の項目が表示されずグレーになっている
     ・Finder での各種の操作の反応が極めて緩慢になる
 4. AquaSKK を Input Souce から削除し，停止する
    ・System Preferences > Keyboard > Input Source で
      AquaSKK を選択し，削除
    ・AquaSKK プロセスを終了
 5. Finder での各種の操作の反応が復旧する

原因と対応
 上掲の症状の原因を探り，深みにはまってしまいました…。が，
 なんとか判りました。

 ・環境設定ウィンドウ中の「変換」タブをクリックして開く設定
   オプション「候補ウィンドウ」の「フォント」に何を指定
   しているかが問題
     初期設定は「Trebuchet MS」です
      … このフォントが OS にロードされていないと発症
  ・いったん，このフォントを OS にロードすると，他は変えな
    いのに AquaSKK の環境設定はできてふつうに使える。
  ・候補ウィンドウ用フォントを別の macOS 必須フォントに変え
    て設定した以降は，Trebuchet MS フォントを削除しても
    AquaSKK の動作には支障がない

疑問と改善(？)の提案
 1. 現状の「候補ウィンドウ用フォントをTrebuchet MS とする」
    初期設定には必要性はあるのか。別のフォントに変えられ
    ない事情があるのか
 2. 別のフォントに変えられない事情があるなら，ReadMe などに
    注意すべきだと思います。
    変えられるなら，例えば macOS の必須フォント Geneva や
    Helvetica などに変更した方がいいのではないでしょうか。

**Comment by mzp** [comment]
なるほど。  たしかにフォントを無効にすると変な挙動になりますね。

初期値を変えるのはちょっと影響が大きすぎるように感じるので、フォントが見付からなかったときの処理の改善を検討します。

**Comment by mzp** [comment]
4.4.6 でフォントがみつからない場合の挙動を改善しました。
