### ISSUE TITLE
候補ウィンドウが出ない/単語登録モードに遷移しない

### ISSUE THREAD

**Issue by mlny** [codefirst/aquaskk#84]
* 一部の単語を入力しようとして何度かSpaceを押すと、本来は候補ウィンドウが出たあと、単語登録モードに遷移するはずですが、候補ウィンドウが出ず単語登録モードに遷移しません。 ( https://mstdn.maud.io/@malony/100644999492829853 )
* アップデートの際に残ったゴミが原因かと思い $HOME/Library/Application Support/AquaSKK の中身全てと、$HOME/Library/jp.sourceforge.inputmethod.aquaskk.plist を削除しましたが、症状は改善しません。
* AquaSKK初期の状態で「きょうこ」を変換しようとすると発生することを確認しています。

AquaSKK 4.6.0(2018-8-31)
macOS High Sierra 10.13.6 17G65

**Comment by mzp** [comment]
う、再現確認しました。 いったん 4.6.0をpre-releaseとしてマークして調査やります。

**Comment by mzp** [comment]
なおして4.6.1としてリリースしました。 ありがとうございます!

**Comment by mlny** [comment]
![2018-09-01 17 50 24](https://user-images.githubusercontent.com/5173607/44944322-8a219800-ae0f-11e8-89bd-c01a3399a298.png)
fixを確認しました。迅速な対応感謝いたします。
