### ISSUE TITLE
Google Chrome のキーワードサーチで最初の文字が残ってしまう

### ISSUE THREAD

**Issue by kyohsuke** [codefirst/aquaskk#89]
Google Chrome でウェブサイト内サーチを利用する際、最初の文字が残ってしまいます。
ごく最近の、Chrome の見た目がちょっと新しくなったあたりから自分の環境では発生していて困っています。

設定で回避する手段などがあれば教えて頂けるとうれしいです。

![help](https://user-images.githubusercontent.com/573880/51073050-bf3bd200-16ae-11e9-81c9-be9b179e8216.gif)

この現象は `<Type search term>` のみ表示されている時にだけ発生し、
また「あ い う え お」は問題が起こりません。

↓ 起こる時のアドレスバー
<img width="530" alt="screen shot 2019-01-12 at 21 20 41" src="https://user-images.githubusercontent.com/573880/51073152-f5c61c80-16af-11e9-8053-4e2cb69162e2.png">

↓起こらない時のアドレスバー
<img width="304" alt="screen shot 2019-01-12 at 21 19 43" src="https://user-images.githubusercontent.com/573880/51073155-01b1de80-16b0-11e9-9cd7-b36b0d9244cd.png">

環境は以下となります。

macOS: Mojave (Version 10.14.2)
AquaSKK: 4.7.0 (2018-10-13)
Google Chrome: Version 71.0.3578.98 (Official Build) (64-bit)

再現方法は以下となります。

1. github.com まで入力
1. `<TAB>` でサイト内サーチに切り替える
1. 何かしら文字を入力する

**Comment by mzp** [comment]
再現は確認しましたが、Chromeの問題なのでAquaSKKで回避は難しいと思います。

Chromium側に同様のバグが報告されていました: https://bugs.chromium.org/p/chromium/issues/detail?id=896962 。

**Comment by kyohsuke** [comment]
なるほど、IME に依存しないどころか Windows でも発生しているもっと根本的な問題なのですね、お手数おかけしました。
