### ISSUE TITLE
ターミナルでcontrolシーケンスが効かない

### ISSUE THREAD

**Issue by vmi** [codefirst/aquaskk#9]
ターミナル以外だと問題ないのですが、ターミナルだとcontrol+Lやcontrol+Q、control+LなどがAquaSKKではなくターミナルに直接渡っているように見えます。
うろ覚えの記憶では以前は問題なかったような気がするので、OSのバージョンアップのせいかもしれません。

OSは10.10.2の最新アップデート適用済みです。

**Comment by mzp** [comment]
以前はどうだったか覚えていないんですが、基本的にOSがAquaSKK(InputMethod)側にC-jなどを渡してこないのが原因です。
回避したパッチ https://github.com/codefirst/aquaskk/pull/5 はあるにはあるんですが、InputMethodの枠を越えちゃいますしどうしようかなぁ、と悩んでます。

**Comment by vmi** [comment]
あー、前からなんですね。
ということは前はいけたと思ったのは勘違いですね。

> InputMethodの枠を越えちゃいますしどうしようかなぁ、と悩んでます。

純利用者的には他で使える機能がターミナルで使えないのはおかしいんですが、OSの枠組みがそうなってるのがややこしいですね。何を思ってそんな変な仕様にしているのか……。

設定ファイルで明示したときのみ有効とか、システム環境設定のショートカットから設定できるようにする(どうやって実現するのかは知らない)とか。

ワークアラウンドとしてはコントロールシーケンス以外の割り当てにしてKarabinerでリマップするくらいでしょうか。

**Comment by vmi** [comment]
用語訂正: ×コントロールシーケンス ○コントロールキーコンビネーション?

**Comment by banjun** [comment]
アプリ(=ターミナル)側が，キーイベントをテキスト入力として扱っていない(InputMethodに渡さない)のかもしれません。アプリとしてはキーコンビネーションに独自機能を割り当てたいということはありそうです。

私は`/Library/Input Methods/AquaSKK.app`内の`keymap.conf`を↓のようにして`~/Library/Application Support/AquaSKK/`下に置いて，ターミナル(かつUS配列)のときはC-9でしのいでいます。

```
SKK_JMODE		ctrl::j||ctrl::9
```

**Comment by mzp** [comment]
Karabinerでのリマップをやりました => [iTerm2/Apple TerminalでAquaSKKを使う - みずぴー日記](http://mzp.hatenablog.com/entry/2015/03/15/213219 "iTerm2/Apple TerminalでAquaSKKを使う - みずぴー日記")

**Comment by banjun** [comment]
:+1:
