### ISSUE TITLE
設定画面 - 辞書を追加する際の挙動について（再）

### ISSUE THREAD

**Issue by elim** [codefirst/aquaskk#94]
（以前 Issue #55 にて起票され、 Pull Reuest #56 解決されたものと同様の現象のようです）

環境
---

* macOS 10.14.4 (18E226)
* AquaSKK 4.7.0 (2018-10-13)
 
現象
---

* 設定画面内の辞書タブを開きあす
* `ユーザー辞書:` の `変更...` より辞書ファイルを選択します
    * すると、先頭に `file:/` という文字がついたファイルのパスが追加されます
* 実際はパスから `file:/` を除去しないと追加した語彙が辞書へ反映されません

![aquaskk-dic-select2](https://user-images.githubusercontent.com/7157/56277018-86444b00-613e-11e9-8038-09e680e7f3dd.gif)

**Comment by banjun** [comment]
`変更...` から、変更したときですね? 再現確認しました :+1:

**Comment by elim** [comment]
> `変更...` から、変更したときですね? 再現確認しました 👍

すみません、その通りです 🙇🏻

**Comment by elim** [comment]
@y-yu @banjun ありがとうございました 🎉
